checkpoint: null
backbone_name: vit_base_patch16_384.augreg_in21k_ft_in1k
resolution: 384
use_steering: true
feature_pool: cls
text_only: false
unfreeze_gca: true
unfreeze_connector: true
cross_attn_layers: [1, 3, 5, 7, 9, 11]
