checkpoint: null
backbone_name: vit_base_patch14_dinov2.lvd142m
resolution: 336
use_steering: true
feature_pool: cls
text_only: false
condition_type: film
unfreeze_gca: true
unfreeze_connector: true
cross_attn_layers: [1, 3, 5, 7, 9, 11]
